10-intro-to-rails/rails_school2/config/routes.rb
Rails.application.routes.draw do
                      'controller#action'  
  get '/students', to: 'students#index', as: 'students'
  get '/students/:id', to: 'students#show', as: 'student'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

10-intro-to-rails/rails_school2/app/models/student.rb
class Student < ApplicationRecord
end

10-intro-to-rails/rails_school2/app/controllers/students_controller.rb
class StudentsController < ApplicationController
  # get /students
  def index 
    @students = Student.all 

    render :index
  end 


  def show 
    @student = Student.find(params[:id])

    # render :show 
  end 
end

10-intro-to-rails/rails_school2/app/helpers/students_helper.rb
module StudentsHelper
end

10-intro-to-rails/rails_school2/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSchool2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

10-intro-to-rails/rails_school2/app/views/students/index.html.erb
<h1>Student Index Page</h1>

<% @students.each do |student| %>
  <p><%= link_to student.name, "/students/#{student.id}" %></p>
  <p><%= link_to student.name, student_path(student.id) %></p>
<% end %>

10-intro-to-rails/rails_school2/app/views/students/show.html.erb
<h1>Student Show Page</h1>

<h3><%= @student.name %></h3>