15-authentication-authorization/shopping_spree/config/routes.rb
Rails.application.routes.draw do
  resources :user_items, only: [:new, :create]
  resources :users, only: [:index, :show, :new, :create]
  resources :items

  patch '/sessions/reset_page', to: 'sessions#reset_page', as: 'session_reset'
  get '/sessions/new', to: 'sessions#new', as: 'new_session'
  post '/sessions', to: 'sessions#login', as: 'login'
  delete '/sessions/logout', to: 'sessions#logout', as: 'logout'

  # For details on the DS L available within this file, see https://guides.rubyonrails.org/routing.html

  # resources :items, except: [:destroy]

  #VERB URL    CONTROLLER#ACTION   HELPER 
  # get '/items', to: "items#index", as: 'items'
  # get '/items/new', to: "items#new", as: 'new_item'
  # get '/items/:id', to: "items#show", as: 'item'
  # get '/items/:id/edit', to: "items#edit", as: 'edit_item'

  # post '/items', to: "items#create"
  # patch '/items/:id', to: "items#update"
  # delete '/items/:id', to: "items#destroy" 
end

15-authentication-authorization/shopping_spree/app/models/item.rb
class Item < ApplicationRecord
  has_many :user_items
  has_many :users, through: :user_items

  # price has to be larger then 500 1000000
  # name has to have a name 
  # name nothing can have the same name
  # category has to be one from a specific list 

  # validates :attribute, :validation_helper :rules
  validates :price, numericality: {greater_than: 500, less_than: 1000000, only_integer: true} 
  validates :name, presence: true
  validates :name, uniqueness: true
  validates :category, inclusion: {in: %w(foods sports hats)}

  validate :name_can_not_be_greg

  def name_can_not_be_greg
    if self.name && self.name.downcase == "greg"
      self.errors.add(:name, "can not be ME!!!!")
    end 

  end
end

15-authentication-authorization/shopping_spree/app/models/user.rb
class User < ApplicationRecord
  has_many :user_items, dependent: :destroy
  has_many :items, through: :user_items

  has_secure_password

  # def password=(secret)
  #   hashed_pass = BCrypt::Password.create(secret)

  #   self.password_digest = hashed_pass
  # end 

  # def password
  #   self.password_digest
  # end
end

15-authentication-authorization/shopping_spree/app/models/user_item.rb
class UserItem < ApplicationRecord
  belongs_to :user, optional: :true
  belongs_to :item
end

15-authentication-authorization/shopping_spree/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authorized

  def set_user
    # @current_user = User.find(id: session[:user_id])
    @current_user = User.find_by(id: session[:user_id])
  end 

  def authorized
    redirect_to new_user_path unless set_user
  end 

end

15-authentication-authorization/shopping_spree/app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :find_item, only: [:show, :edit, :update, :destroy]

  def index
    @items = Item.all

    # render :index
  end 

  def show 
    # @item = Item.find(params[:id])

    if session[:page_count]
      session[:page_count] = session[:page_count] + 1
    else 
      session[:page_count] = 1
    end
    # render :show
  end

  def new
    @item = Item.new
  
    render :new
  end 
  
  def create 
    @item = Item.create(item_params) 

    # @item = Item.new(item_params) 
    # if @item.save

    if @item.valid?
      flash[:success] = "SWEET NEW ITEM"
      redirect_to item_path(@item)
    else 
      flash[:my_errors] = @item.errors.full_messages
      redirect_to new_item_path 
    end 
    # redirect_to item_path(item.id)
    # redirect_to item
  end 

  def edit 
    # @item = Item.find(params[:id])
  end 

  def update 
    # @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to item_path(@item)
    else
      flash[:my_errors] = @item.errors.full_messages 
      redirect_to edit_item_path
    end 

    
  end 
  
  def destroy 
    # @item = Item.find(params[:id])
    @item.destroy 

    redirect_to items_path
  end 


  private 

  def item_params
    params.require(:item).permit(:name, :price, :category, :img_url)
  end 

  def find_item
    @item = Item.find(params[:id])
  end 

end

15-authentication-authorization/shopping_spree/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authorized, only: [:new, :login]
  def new 
    render :login
  end 

  def login
    user = User.find_by(name: params[:session][:name])

    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id 
      redirect_to user_path(user)
    else 
      flash[:error] = "Username or Password is incorrect"
      redirect_to new_session_path
    end 
    
  end 
  
  def logout 
    # session[:user_id] = nil 
    session.delete(:user_id)
    redirect_to new_user_path

  end 

  def reset_page
    cookies[:page_count] = 0
    
    redirect_back fallback_location: items_path
  end

end

15-authentication-authorization/shopping_spree/app/controllers/user_items_controller.rb
class UserItemsController < ApplicationController

  def new 
    @user_item = UserItem.new

    @users = User.all
    @items = Item.all
  end
  
  def create 
    # @current_user
    UserItem.create(user_id: @current_user.id,  item_id: params[:user_item][:item_id])
    # .user_items << UserItem.create(user_item_params)
    # byebug
    # redirect_to user_path(@user_item.user_id)
    redirect_to user_path(@current_user)
  end 

  private 

  def user_item_params
    params.require(:user_item).permit(:item_id)
  end 
end

15-authentication-authorization/shopping_spree/app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authorized, only: [:new, :create]

  def index 
    @users = User.all
  end 

  def show 
    @user = User.find(params[:id])

    if @user == @current_user 
      render :show 
    else 
      flash[:error] = "Can only See Your Own Profile"
      redirect_to users_path
    end 

  end 

  def new 
    @user = User.new
  end 

  def create 
    user = User.create(user_params)

    if user.valid? 
      session[:user_id] = user.id

      redirect_to user_path(user)
    else 
      flash[:errors] = user.errors.full_messages
      redirect_to new_user_path
    end 

  end 

  private 

  def user_params 
    params.require(:user).permit(:name, :slogan, :img_url, :password)
  end 
end

15-authentication-authorization/shopping_spree/app/helpers/application_helper.rb
module ApplicationHelper
end

15-authentication-authorization/shopping_spree/app/helpers/items_helper.rb
module ItemsHelper
end

15-authentication-authorization/shopping_spree/app/helpers/sessions_helper.rb
module SessionsHelper
end

15-authentication-authorization/shopping_spree/app/helpers/user_items_helper.rb
module UserItemsHelper
end

15-authentication-authorization/shopping_spree/app/helpers/users_helper.rb
module UsersHelper
end

15-authentication-authorization/shopping_spree/app/views/items/_ad.html.erb
<h1>Watch Ad</h1>

<iframe width="966" height="543" src="https://www.youtube.com/embed/ZCpf0LNYsYA" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>


<%= button_to 'I Super Promise I Watched This Ad', session_reset_path, method: :patch %>

15-authentication-authorization/shopping_spree/app/views/items/_form.html.erb
<% if flash[:my_errors] %>
  <% flash[:my_errors].each do |error| %>
    <p style="color: red;"><%= error %></p>
  <% end %>
<% end %>

<%= form_for @item do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :price %>
  <%= f.number_field :price %>

  <%= f.label :category %>
  <%= f.text_field :category %>

  <%= f.label :img_url %>
  <%= f.text_field :img_url %>
  
  <%= f.submit %>
<% end %>

15-authentication-authorization/shopping_spree/app/views/items/edit.html.erb
<div class="container">
  <h1>Edit Item</h1>

  <%= render 'form' %>
</div>

15-authentication-authorization/shopping_spree/app/views/items/index.html.erb
<div class="index-container container">

  <% @items.each do |item| %>
    <div class="index-tile">
      <h3><%=link_to item.name, item_path(item.id) %></h3>
      <img class="index-img" src="<%= item.img_url %>" alt="<%= item.name%>">
      <%= button_to "X", item, method: :delete, class: 'btn' %>
    </div>
  <% end %>
</div>

15-authentication-authorization/shopping_spree/app/views/items/new.html.erb
<div class="container">
  <h1>Create Item</h1>

  <%= render 'form' %>
</div>

15-authentication-authorization/shopping_spree/app/views/items/show.html.erb
<div class="container">
  <% if session[:page_count].to_i <= 3 %>

  <h1><%= 3 - session[:page_count].to_i %>Page Views Left</h1>

  <% if flash[:success] %>
    <h1><%= flash[:success] %></h1>
  <% end %>
  
  <h1>Item Show Page</h1>

  <h3><%= @item.name %></h3>
  <p>Price: $<%= @item.price %></p>
  <p>Category: <%= @item.category %></p>


  <marquee><img src="<%= @item.img_url %>" alt="<%= @item.name%>" class="show-img"></marquee>

  <%= button_to "DELETE", item_path(@item), method: :delete %>

  <% else %>
    <%= render 'ad' %>
  <% end %>
</div>

15-authentication-authorization/shopping_spree/app/views/users/index.html.erb
 <% if flash[:error] %>
  <p><%= flash[:error] %></p>
 <% end %>
<div class="index-container container">

  <% @users.each do |user| %>
    <div class="index-tile">
      <p><%# link_to user.name, user_path(user)  %></p>
      <p><%= link_to user.name, user  %></p>
      <img src="<%= user.img_url %>" alt="<%= user.name%>" class="index-img" >
    </div>
  <% end %>

</div>

15-authentication-authorization/shopping_spree/app/views/users/new.html.erb
<div class="container">
  <h1>Create New User</h1>

  <% if flash[:errors] %>
    <% flash[:errors].each do |error| %>
      <p style="color: red;"><%= error %></p>
    <% end %>
  <% end %>


  <%= form_for @user do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.label :password %>
    <%= f.text_field :password %>

    <%= f.label :slogan %>
    <%= f.text_field :slogan %>

    <%= f.label :img_url %>
    <%= f.text_field :img_url %>

    <%= f.submit %>
  <% end %>
</div>

15-authentication-authorization/shopping_spree/app/views/users/show.html.erb
<div class='container'>
  <h1>User Show</h1>


  <h3> <%= @user.name %> </h3>
  <p> <%= @user.slogan %> </p>

  <marquee> <img src="<%= @user.img_url %>" alt="<%= @user.name %>" class="show-img"> </marquee>

  <h1>All of My Items</h1>

  <% @user.items.each do |item| %>
    <p><%= item.name %></p>
  <% end %>
</div>