14-cookies-and-session/shopping_spree/config/routes.rb
Rails.application.routes.draw do
  resources :user_items, only: [:new, :create]
  resources :users, only: [:index, :show]
  resources :items

  patch '/sessions/reset_page', to: 'sessions#reset_page', as: 'session_reset'

  # For details on the DS L available within this file, see https://guides.rubyonrails.org/routing.html

  # resources :items, except: [:destroy]

  #VERB URL    CONTROLLER#ACTION   HELPER 
  # get '/items', to: "items#index", as: 'items'
  # get '/items/new', to: "items#new", as: 'new_item'
  # get '/items/:id', to: "items#show", as: 'item'
  # get '/items/:id/edit', to: "items#edit", as: 'edit_item'

  # post '/items', to: "items#create"
  # patch '/items/:id', to: "items#update"
  # delete '/items/:id', to: "items#destroy" 
end

14-cookies-and-session/shopping_spree/app/models/user_item.rb
class Pet < ApplicationRecord
  belongs_to :user, optional: :true
  belongs_to :item
end

14-cookies-and-session/shopping_spree/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index 
    @users = User.all
  end 

  def show 
    @user = User.find(params[:id])
  end 
end

14-cookies-and-session/shopping_spree/app/views/items/_form.html.erb
<% if flash[:my_errors] %>
  <% flash[:my_errors].each do |error| %>
    <p><%= error %></p>
  <% end %>
<% end %>

<%= form_for @item do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :price %>
  <%= f.number_field :price %>

  <%= f.label :category %>
  <%= f.text_field :category %>

  <%= f.label :img_url %>
  <%= f.text_field :img_url %>
  
  <%= f.submit %>
<% end %>

14-cookies-and-session/shopping_spree/app/views/items/edit.html.erb
<h1>Edit Item</h1>

<%= render 'form' %>

14-cookies-and-session/shopping_spree/app/views/items/index.html.erb
<h1>Items Index Page</h1>
<div class="index-container container">

  <% @items.each do |item| %>
    <div class="index-tile">
      <h3><%=link_to item.name, item_path(item.id) %></h3>
      <img class="index-img" src="<%= item.img_url %>" alt="<%= item.name%>">
      <%= button_to "X", item, method: :delete, class: 'btn' %>
    </div>
  <% end %>
</div>

14-cookies-and-session/shopping_spree/app/views/items/new.html.erb
<h1>Create Item</h1>

<%= render 'form' %>

14-cookies-and-session/shopping_spree/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ShoppingSpree</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

14-cookies-and-session/shopping_spree/app/views/users/index.html.erb
<h1>All Users</h1>

<div class="index-container container">

  <% @users.each do |user| %>
    <div class="index-tile">
      <p><%# link_to user.name, user_path(user)  %></p>
      <p><%= link_to user.name, user  %></p>
      <img src="<%= user.img_url %>" alt="<%= user.name%>" class="index-img" >
    </div>
  <% end %>

</div>

14-cookies-and-session/shopping_spree/app/views/users/show.html.erb
<h1>User Show</h1>


<h3> <%= @user.name %> </h3>
<p> <%= @user.slogan %> </p>

<marquee> <img src="<%= @user.img_url %>" alt="<%= @user.name %>"> </marquee>

<h1>All of My Items</h1>

<% @user.items.each do |item| %>
  <p><%= item.name %></p>
<% end %>